name: PlasmoVoice
version: ${project.version}
main: su.plo.voice.PlasmoVoice
api-version: 1.16
authors: [ Apehum ]
softdepend:
  - PlaceholderAPI

commands:
  vmute:
    permission: voice.mute
  vunmute:
    permission: voice.unmute
  vmutelist:
    permission: voice.mutelist
  vreload:
    permission: voice.reload
  vreconnect:
    permission: voice.reconnect
    aliases:
      - vrc
  vlist:
    permission: voice.list

permissions:
  voice.list:
    default: true
  voice.priority:
    default: op
  voice.reconnect:
    default: true
  voice.reload:
    default: op
  voice.mute:
    default: op
  voice.unmute:
    default: op
  voice.mutelist:
    default: op
  voice.speak:
    default: true
  voice.activation:
    default: true